name: ncryptor
description: "internal prototype"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  process_run: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
