name: Flutter Linux Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        type: string

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
      
      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop
      
      - name: Flutter pub get
        run: flutter pub get
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Create Linux tarball
        run: |
          cd build/linux/x64/release/bundle
          tar -czf ../../../../../linux-release.tar.gz *
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: linux-release.tar.gz

  release:
    name: Create GitHub Release
    needs: [build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
          tag_name: ${{ inputs.version }}
          files: |
            linux-release/linux-release.tar.gz
          body: |
            ## Release ${{ inputs.version }}
            
            ### Downloads
            - **Linux**: [TAR.GZ](https://github.com/${{ github.repository }}/releases/download/v${{ inputs.version }}/linux-release.tar.gz)
